require 'fileutils'

tests =
[
['slab','USA_DC_Washington'],
['basement','USA_IL_Chicago'],
['crawlspace','USA_FL_Tampa']
]


def run(example, weather)
	FileUtils::mkdir_p("#{example}-#{weather}")
	system("../builds/debug/kiva ../examples/#{example}.yaml ../weather/#{weather}.epw #{example}-#{weather}/output.csv")
end



desc "Run tests"
task :test, [:number] do |t, args|
	if args.number
	  tests = [tests[args.number.to_i-1]]
	end
	i = 1
	for t in tests
		puts "Running test #{i} of #{tests.length}..."
		puts "\n"
		puts "File: " + t[0] + ".yaml"
		puts "Weather: " + t[1] + ".epw"
		puts "\n"
		run(t[0],t[1])
		i += 1
		puts "\n"
	end
end

task :default => :test
