
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 21.6.0 - x86_64
...
