name: Build and Test

on: push

env:
  RT_URL: github.com/bigladder/kiva-test-results.git
  RT_DIR: build/test/results
  PATOKEN: ${{ secrets.CI_PA_TOKEN }}
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu
            os_ver: "22.04"
            config: Release
            coverage: false
            cc: gcc-11
            cxx: g++-11
          - os: ubuntu
            os_ver: "20.04"
            config: Release
            coverage: false
            cc: gcc-10
            cxx: g++-10
          - os: windows
            os_ver: "2022"
            config: Release
            coverage: false
            cc: cl
            cxx: cl
          - os: macos
            os_ver: "12"
            config: Release
            coverage: false
            cc: clang
            cxx: clang++
          - os: macos
            os_ver: "11"
            config: Release
            coverage: false
            cc: clang
            cxx: clang++
          - os: ubuntu
            os_ver: "20.04"
            config: Debug
            coverage: true
            cc: gcc-10
            cxx: g++-10
    defaults:
      run:
        shell: bash
    name: ${{ matrix.os }}-${{ matrix.os_ver }} ${{ matrix.cxx }} ${{ matrix.config }} coverage=${{ matrix.coverage }}
    env: 
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    runs-on: ${{ matrix.os }}-${{ matrix.os_ver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Kiva
        uses: ./.github/actions/build-kiva
        with:
          configuration: ${{ matrix.config }}
          coverage: ${{ matrix.coverage }}
      - name: Run tests and log results
        if: "!matrix.coverage"
        run: |
          ctest -C ${{matrix.config}} --output-on-failure
          ruby ../scripts/log-results.rb
        working-directory: build
      - name: Unit tests
        if: "matrix.coverage"
        run: |
          ctest -R unit\.
          make gcov
        working-directory: build
      - name: Upload Code Coverage Report (Unit)
        if: "matrix.coverage"
        uses: codecov/codecov-action@v2
        with:
          flags: unit
      - name: Integration tests
        if: "matrix.coverage"
        run: |
          ctest -R integration\.
          make gcov
        working-directory: build
      - name: Upload Code Coverage Report (Integration)
        if: "matrix.coverage"
        uses: codecov/codecov-action@v2
        with:
          flags: integration

