name: Release

on:
  release:
    types:
      - created

jobs:
  deploy-release:
    name: Deploy Release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get branch name
        uses: tj-actions/branch-names@v5
        id: branch-name

      - name: Save branch name
        run: |
          echo "SRC_BRANCH=${{steps.branch-name.outputs.current_branch}}" >> $GITHUB_ENV

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Install Linux Libraries
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get -y install libglu1-mesa-dev freeglut3-dev mesa-common-dev

      - name: Configure CMake
        run: cmake -S . -B build -DKIVA_COVERAGE="${{ matrix.coverage }}" -DKIVA_STATIC_LIB="${{ matrix.static_lib }}" -DCMAKE_BUILD_TYPE="${{ matrix.config }}"

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Package
        run: cpack -C Release -B ${{github.workspace}}

      - name: Upload executable to release assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: kiva*.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
