name: Release

on:
  release:
    types:
      - created

jobs:
  deploy-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu
            os_ver: "20.04"
            cc: gcc-10
            cxx: g++-10
          - os: windows
            os_ver: "2022"
            cc: cl
            cxx: cl
          - os: macos
            os_ver: "11"
            cc: clang
            cxx: clang++
    defaults:
      run:
        shell: bash
    name: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    runs-on: ${{ matrix.os }}-${{ matrix.os_ver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Kiva
        uses: ./.github/actions/build-kiva
      - name: Package
        run: cpack -C Release
        working-directory: build
      - name: Upload executable to release assets
        uses: AButler/upload-release-assets@v2.0.2
        with:
          files: build/kiva*.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
